///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChangePasswordModel {
/*
{
  "success": true,
  "message": "Password is changed",
  "responsecode": 200
} 
*/

  bool? success;
  String? message;
  int? responsecode;

  ChangePasswordModel({
    this.success,
    this.message,
    this.responsecode,
  });
  ChangePasswordModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    responsecode = json['responsecode']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['responsecode'] = responsecode;
    return data;
  }
}
