///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ForgetModel {
/*
{
  "success": true,
  "message": "Check your email address for reset password",
  "data": "",
  "responsecode": 200
} 
*/

  bool? success;
  String? message;
  String? data;
  int? responsecode;

  ForgetModel({
    this.success,
    this.message,
    this.data,
    this.responsecode,
  });
  ForgetModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = json['data']?.toString();
    responsecode = json['responsecode']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['data'] = this.data;
    data['responsecode'] = responsecode;
    return data;
  }
}
