///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelData {


  String? token;
  String? name;
  String? email;
  int? id;

  LoginModelData({
    this.token,
    this.name,
    this.email,
    this.id,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['name'] = name;
    data['email'] = email;
    data['id'] = id;
    return data;
  }
}

class LoginModel {
/*
{
  "success": true,
  "data": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3Y1LmNoZWNrcHJvamVjdHN0YXR1cy5jb20vZXZvbHZlL3B1YmxpYy9hcGkvdjEvbG9naW4iLCJpYXQiOjE3MTAxNDEwNjUsImV4cCI6MTcxMDE0NDY2NSwibmJmIjoxNzEwMTQxMDY1LCJqdGkiOiJPQlJqTHA3R2NhMmxGVUVDIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.xNV_VcOpoiKoV3OlNshqBHRgUDjtIjElMCQujcYQcAM",
    "name": "Shyam Singh",
    "email": "himanshu001@yopmail.com",
    "id": 1
  },
  "message": "Great! You have Successfully logged in."
} 
*/

  bool? success;
  LoginModelData? data;
  String? message;

  LoginModel({
    this.success,
    this.data,
    this.message,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? LoginModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}

